name: "Exemplo de CD"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: docker pull viixtiin/exemplo-ci

      - name: Stop Docker container
        run: docker stop exemplo-ci || true

      - name: Remove Docker container
        run: docker rm exemplo-ci || true

      - name: Run Docker container
        run: docker run --name exemplo-ci -d -p 8080:8080 viixtiin/exemplo-ci:latest