name: Exemplo de CI # Nome da ação

on:
    push: # Evento que irá disparar a ação
      branches: [ main ] # Branch que irá disparar a ação

jobs: # Trabalhos a serem executados
    build: # Nome do trabalho pode ser qualquer um de sua escolha
      runs-on: ubuntu-latest # Sistema qoperacional a ser utilizado
      steps: # Passos a serem executados
        - name: Checkout code # Nome do passo, clonar o repositorio
          uses: actions/checkout@v4 # action escolhida.

        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '17'

        - name: Build with Maven
          run: mvn -B package -DskipTests